FROM python:3.11

# Set up the directory and install dependencies
WORKDIR /app
ADD requirements-train.txt /app/requirements.txt
RUN pip install -r requirements.txt

# Add the code as the last Docker layers because it changes the most
ADD mnist_net.py  /app/mnist_net.py
ADD train.py  /app/train.py
ADD config.py  /app/config.py

# Run the service
CMD [ "python", "train.py", "--batch-size", "128", "--epochs", "1", "--save-model"]