apiVersion: batch/v1
kind: Job
metadata:
  name: train-job
spec:
  template:
    metadata:
      labels:
        app: train-job
    spec:
      containers:
      - name: train-job
        image: lvb243/cml:train-image
        volumeMounts:
        - name: storage-volume
          mountPath: /mounted_volume
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: persistent-volume
      restartPolicy: Never
